### PR TITLE
[Enhancement] Add Generation to meow lookup

### PR DESCRIPTION
**Pull request by zzeleznick**
## Description
This PR adds the generation information to the command `meow lookup`

## Changes
- adds a `.gitignore`
- organizes imports of core props for `index.js`
- adds  `Generation` to `meow lookup`

## Example
```
$ meow loookup 10628
Kitty #10628
  Birthdate:    2017-12-01 23:17:05
  Owner:        0x88b8601E1679AbDe44332F0e3eFF32396fcDaA2D
  Generation:   5
  Busy Until:   4679125
  Genes:        0x5a12b318851a46e421ee18000310c67396e08146218e7318e343dcf639ae
  Matron Id:    10342
  Sire Id:      10258
  Siring With:  0
  URL:          https://www.cryptokitties.co/kitty/10628
```

## Tests
- [x] verified `meow lookup` returns expected output

### CODE REVIEW

**Comment by ricmoo** [comment]
Can you move the meow output back to alphabetical order?

Then it looks good and I'll merge. :)

**Comment by zzeleznick** [comment]
@ricmoo: sure thing.

**Comment by ricmoo** [comment]
Sorry to bug you one last time, but `Matron Id` comes before `Owner`. :)

In the future the number of output parameters will get much longer, so it is important to be able to find the values you are looking for...

**Comment by zzeleznick** [comment]
That was a brain fart there. I originally tried to sort based on a relative hierarchy -- so keys `Matron Id` and `Sire Id` would follow after one another -- but alphabetical works too.

**Comment by ricmoo** [comment]
LOL! No worries, it happens.

I will be adding cattributes, imageUrl and all that jazz too. My current version has auctions enabled, but needs more testing, and the cost of testing just got crazy.

I'm hoping to get it up tomorrow, along with auto-breed:

```
/home/ricmoo> meow --account account.json --auto-breed 1001 3021 5674 2566 100
```

Which will continuously look for random valid pairs between the kitty IDs whenever they aren't resting. It was running for over a day until the 0.015 birthing fee kicked in; then I stopped it.

**Comment by ricmoo** [comment]
Thanks again!

**Comment by zzeleznick** [comment]
Cool!

The imageUrl seems to be `https://storage.googleapis.com/ck-kitty-image/$contractAddress/$kittyId.svg` and `contractAddress` is just [`0x06012c8cf97bead5deae237070f9587f8e7a266d`](https://etherscan.io/address/0x06012c8cf97bead5deae237070f9587f8e7a266d#readContract)

EDIT: I have a hunch that is the`.svg` is not resolvable and `.png` is, you've got a fancy cat on your hands: 
* [Genesis](https://storage.googleapis.com/ck-kitty-image/0x06012c8cf97bead5deae237070f9587f8e7a266d/1.png)
* [Vampire](https://storage.googleapis.com/ck-kitty-image/0x06012c8cf97bead5deae237070f9587f8e7a266d/38238.png)
* [Glitch 1](https://storage.googleapis.com/ck-kitty-image/0x06012c8cf97bead5deae237070f9587f8e7a266d/101.png) [Glitch 2](https://storage.googleapis.com/ck-kitty-image/0x06012c8cf97bead5deae237070f9587f8e7a266d/101.png) [Glitch 3](https://storage.googleapis.com/ck-kitty-image/0x06012c8cf97bead5deae237070f9587f8e7a266d/101.png)

How do you read `cattributes`?

**Comment by ricmoo** [comment]
Actually, that url only works for non-fancy cats; fancy cats need the API to figure out the image.

You have to hit their API for cattributes too. I've also got a script mining them into a CSV, just trying to figure out a better way to host them (prolly IPFS), so their servers don't get smashed by all the data-mining bots.

**Comment by zzeleznick** [comment]
@ricmoo: I'm curious how [`cryptokittydex`](https://cryptokittydex.com/) queries the cattributes.

I'd also like to add fetching your kitty Id's via your address using their API.

**Pull request merged**
